!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  RIP CONFIGURATION
!
!
router rip
! la network da distribuire
network 100.0.0.0/8
network 2.2.2.2/32
!
! abilitazione della redistribuzione BGP in RIP
redistribute bgp route-map eBGP
redistribute connected
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 100
! QUALE  NO BGP SERVE? 
no bgp network import-check 
!
! NEIGHBORS
!
neighbor 50.7.1.7 remote-as 7
neighbor 50.7.1.7 description rxa4
neighbor 3.3.3.3 remote-as 100
neighbor 3.3.3.3 update-source 2.2.2.2
neighbor 3.3.3.3 next-hop-self
!
! NETWORKS
!
network 100.0.0.0/8
network 50.7.1.0/24
!
!
!
neighbor 50.7.1.7 prefix-list neighborsevenOut out
neighbor 50.7.1.7 prefix-list neighborsevenIn in
ip prefix-list neighborsevenIn permit any
ip prefix-list neighborsevenOut permit any
!
ip prefix-list neighbor7 permit 50.7.1.7/32 le 32
route-map eBGP permit 10
match ip nexthop prefix-list neighbor7
