!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 4
! QUALE  NO BGP SERVE? 
 no bgp network import-check 
!
! NEIGHBORS
!
neighbor 10.1.5.1 remote-as 1
neighbor 10.1.4.1 remote-as 1
neighbor 10.2.4.1 remote-as 2
!
! NETWORKS
!
network 4.0.0.0/24
!
! POLICIES
!
neighbor 10.1.4.1 prefix-list providerASr1_Out out
neighbor 10.1.4.1 prefix-list providerAS1r1_In in
neighbor 10.1.5.1 prefix-list providerAS1r2_Out out
neighbor 10.1.5.1 prefix-list providerAS1r2_In in
neighbor 10.2.4.1 prefix-list peerOut out
neighbor 10.2.4.1 prefix-list peerIn in
!
!
!
ip prefix-list providerAS1r1_In permit any
ip prefix-list providerASr1_Out permit 4.0.0.0/24

ip prefix-list providerAS1r2_In permit any
ip prefix-list providerAS1r2_Out permit 4.0.0.0/24

ip prefix-list peerIn permit any
ip prefix-list peerOut permit 4.0.0.0/24
!
!
!
! ROUTE map
!
!access-list <ACCESS_LIST_NAME> permit <IP_ADDRESS/NETMASK>
!
!
!route-map <ROUTE_MAP_NAME> permit 10
!	match ip address <ACCESS_LIST_NAME>
!	set <ATTRIBUTE_NAME> <VALUE>
!