!
!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 100
! QUALE  NO BGP SERVE? 
 no bgp ebgp-requires-policy 
! no bgp network import-check 
!
! NEIGHBORS
!
neighbor 50.100.10.2 remote-as 10
neighbor 50.100.10.2 description r10
!
! NETWORKS
!
network 100.100.0.0/16
!
! POLICIES
!
!neighbor <IP_ADDRESS> prefix-list <PREFIX_LIST_NAME> out
!neighbor <IP_ADDRESS> route-map <ROUTE_MAP_NAME> out
!
!
!
!ip prefix-list <PREFIX_LIST_NAME> permit <IP_ADDRESS/NETMASK>
!
!
!
! ROUTE map
!
!access-list <ACCESS_LIST_NAME> permit <IP_ADDRESS/NETMASK>
!
!
!route-map <ROUTE_MAP_NAME> permit 10
!	match ip address <ACCESS_LIST_NAME>
!	set <ATTRIBUTE_NAME> <VALUE>
!
