!
!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 10
! QUALE  NO BGP SERVE? 
! no bgp network import-check 
!
! NEIGHBORS
!
neighbor 50.10.1.2 remote-as 1
neighbor 50.10.1.2 description r1
neighbor 110.220.0.1 remote-as 20
neighbor 110.220.0.1 description r20
neighbor 50.100.10.4 remote-as 100
neighbor 50.100.10.4 description r100
!
! NETWORKS
!
network 110.220.0.0/24
network 100.10.0.0/16
network 50.100.10.0/24
!
! POLICIES
!
neighbor 50.50.1.2 prefix-list providerOut out
neighbor 50.50.1.2 prefix-list providerIn in
neighbor 110.220.0.1 prefix-list peerOut out
neighbor 110.220.0.1 prefix-list peerIn in
neighbor 50.100.10.4 prefix-list customerOut out
neighbor 50.100.10.4 prefix-list customerIn in
!
!
!
ip prefix-list providerIn permit any
ip prefix-list providerOut permit 110.10.0.0/16
ip prefix-list providerOut permit 50.100.10.0/24
ip prefix-list providerOut permit 100.100.0.0/16
!
ip prefix-list peerIn permit any
ip prefix-list peerOut permit 100.10.0.0/16
ip prefix-list peerOut permit 50.100.10.0/24
ip prefix-list peerOut permit 100.100.0.0/16
!
ip prefix-list customerIn permit any
ip prefix-list customerOut permit any
! ROUTE map
!
!access-list <ACCESS_LIST_NAME> permit <IP_ADDRESS/NETMASK>
!
!
!route-map <ROUTE_MAP_NAME> permit 10
!	match ip address <ACCESS_LIST_NAME>
!	set <ATTRIBUTE_NAME> <VALUE>
!
