!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  RIP CONFIGURATION
!
router rip
! la network da distribuire
network <IP/NETMASK>
! abilitazione della redistribuzione BGP in RIP
redistribute bgp
!
!per redistribuire rotte connesse
!redistribute connected
!per annunciare una certa rotta su rip
!route <IP/NETMASK>
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp <AS_NUMBER>
! QUALE  NO BGP SERVE? 
! no bgp ebgp-requires-policy 
! no bgp network import-check 
!
! NEIGHBORS
!
neighbor <IP_ADDRESS> remote-as <AS_NUMBER>
neighbor <IP_ADDRESS> description <router name>
!
! NETWORKS
!
network <IP_ADDRESS/NETMASK>
!
! POLICIES
!
!neighbor <IP_ADDRESS> prefix-list <PREFIX_LIST_NAME> out
!neighbor <IP_ADDRESS> route-map <ROUTE_MAP_NAME> out
!
!
!
!ip prefix-list <PREFIX_LIST_NAME> permit <IP_ADDRESS/NETMASK>
!
!
!
! ROUTE map
!
!access-list <ACCESS_LIST_NAME> permit <IP_ADDRESS/NETMASK>
!
!
!route-map <ROUTE_MAP_NAME> permit 10
!	match ip address <ACCESS_LIST_NAME>
!	set <ATTRIBUTE_NAME> <VALUE>
!
!
! EXAMPLE CONFIGURATION SNIPPEts of loopback configuration
!neighbor 2.2.2.2 remote-as 100
!neighbor 2.2.2.2 update-source 3.3.3.3
!neighbor 2.2.2.2 next-hop-self
! e ridistribuisci la barra 32 su igp!
!
! e su bgp conf :
!ip prefix-list neighbor7 permit 50.7.1.7/32 le 32
!route-map eBGP permit 10
!match ip nexthop prefix-list neighbor7
!anche con no bgp ebgp-requires-policy
! se servono policy assicurati di fare prefix in e out permit any per questo tratto!