!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 2
! QUALE  NO BGP SERVE? 
 no bgp network import-check 
!
! NEIGHBORS
!
neighbor 10.1.2.1 remote-as 1
neighbor 10.2.4.2 remote-as 4
neighbor 10.2.3.2 remote-as 3
!
! NETWORKS
!
network 2.0.0.0/24
network 10.2.4.0/30
network 10.2.3.0/30
!
! POLICIES
!
neighbor 10.1.2.1 prefix-list providerOut out
neighbor 10.1.2.1 prefix-list providerIn in
neighbor 10.2.4.2 prefix-list peerOut out
neighbor 10.2.4.2 prefix-list peerIn in
neighbor 10.2.3.2 prefix-list customerIn in
neighbor 10.2.3.2 prefix-list customerOut out
!
!
!
ip prefix-list customerIn permit any
ip prefix-list customerOut permit any
!
!
ip prefix-list peerIn permit any
ip prefix-list peerOut permit 10.2.3.0/30
ip prefix-list peerOut permit 2.0.0.0/24
ip prefix-list peerOut permit 3.0.0.0/8
!
ip prefix-list providerIn permit any
ip prefix-list providerOut permit 2.0.0.0/24
ip prefix-list providerOut permit 10.2.3.0/30
ip prefix-list providerOut permit 3.0.0.0/8
! ROUTE map
!
!access-list <ACCESS_LIST_NAME> permit <IP_ADDRESS/NETMASK>
!
!
!neighbor <IP_ADDRESS> route-map <ROUTE_MAP_NAME> out
!route-map <ROUTE_MAP_NAME> permit 10
!	match ip address <ACCESS_LIST_NAME>
!	set <ATTRIBUTE_NAME> <VALUE>
!
!