!
!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 1
! QUALE  NO BGP SERVE? 
 no bgp ebgp-requires-policy 
! no bgp network import-check 
!
! NEIGHBORS
!
neighbor 101.202.0.1 remote-as 2
neighbor 101.202.0.1 description r2
neighbor 50.10.1.4 remote-as 10
neighbor 50.10.1.4 description r10
!
! NETWORKS
!
network 100.1.0.0/16
network 101.202.0.0/24
network 50.10.1.0/24
!
! POLICIES
!
!neighbor <IP_ADDRESS> prefix-list <PREFIX_LIST_NAME> out
!neighbor <IP_ADDRESS> route-map <ROUTE_MAP_NAME> out
!
!
!
!ip prefix-list <PREFIX_LIST_NAME> permit <IP_ADDRESS/NETMASK>
!
!
!
! ROUTE map
!
!access-list <ACCESS_LIST_NAME> permit <IP_ADDRESS/NETMASK>
!
!
!route-map <ROUTE_MAP_NAME> permit 10
!	match ip address <ACCESS_LIST_NAME>
!	set <ATTRIBUTE_NAME> <VALUE>
!
