!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 8
! QUALE  NO BGP SERVE? 
 no bgp ebgp-requires-policy 
 no bgp network import-check 
!
! NEIGHBORS
!
neighbor 89.89.89.2 remote-as 9
!
! NETWORKS
!
network 8.8.8.0/24
!