!
! FRRouting configuration file
!
!
!  OSPF CONFIGURATION

!
router ospf
! Speak OSPF on all interfaces falling in the listed subnets
network 2.0.0.0/8 area 0.0.0.0
redistribute connected
redistribute kernel
redistribute bgp
!
log file /var/log/frr/frr.log
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 2
 no bgp ebgp-requires-policy 
 no bgp network import-check 
!
! NEIGHBORS
!
neighbor 20.10.0.1 remote-as 1
neighbor 20.10.0.1 description as1r3
!
! NETWORKS
!
network 2.0.0.0/8