!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  RIP CONFIGURATION
!
!
router rip
! la network da distribuire
network 100.0.0.0/8
network 3.3.3.3/32
! abilitazione della redistribuzione BGP in RIP
redistribute bgp route-map eBGP
!
!per redistribuire rotte connesse
redistribute connected
!per annunciare una certa rotta su rip
!route <IP/NETMASK>
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 100
! QUALE  NO BGP SERVE? 
 no bgp network import-check 
!
! NEIGHBORS
!
neighbor 50.3.8.8 remote-as 8
neighbor 50.3.8.8 description rdy8
neighbor 2.2.2.2 remote-as 100
neighbor 2.2.2.2 update-source 3.3.3.3
neighbor 2.2.2.2 next-hop-self
!
! NETWORKS
!
network 100.0.0.0/8
network 50.3.8.0/24
!
!
neighbor 50.3.8.8 prefix-list eightOut out
neighbor 50.3.8.8 prefix-list eightIn in
!
!
ip prefix-list eightIn permit any
ip prefix-list eightOut permit any
!
!
!
ip prefix-list neighbor permit 50.3.8.8/32 le 32
route-map eBGP permit 10
match ip nexthop prefix-list neighbor
