!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  RIP CONFIGURATION
!
router rip
network 1.0.0.0/8
redistribute connected
redistribute bgp
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 1
    no bgp ebgp-requires-policy 
    no bgp network import-check 
    !
    ! NEIGHBORS
    !
    neighbor 10.20.0.2 remote-as 2
    neighbor 10.20.0.2 description as2r1
    neighbor 10.20.0.2 default-originate
    neighbor 20.10.0.2 remote-as 2
    neighbor 20.10.0.2 description as2r5
    neighbor 20.10.0.2 default-originate
    !
    ! NETWORKS
    !
    network 1.0.0.0/8
